# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74d8689a5dbc92e7cb7742d68dfe9e09ec3fca822d49467867d5b255e8dc7162dcc3d3b4873ffd9050dc6a1a0e3f055a26def345a1c9bf18a4d0716dbf996c4c

test:
  secret_key_base: 03f6b998356364cc75b94e8f9d4c114add6763ccfe630014cc57180a327595bc06d81b5a01291b06688f66db59a852e80fdaef6258256322c2f4db8e750eba33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
